[2024-10-01T08:52:41.459+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-01T08:52:41.564+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.remove_file scheduled__2024-09-05T00:00:00+00:00 [queued]>
[2024-10-01T08:52:41.573+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.remove_file scheduled__2024-09-05T00:00:00+00:00 [queued]>
[2024-10-01T08:52:41.574+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-01T08:52:41.659+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): remove_file> on 2024-09-05 00:00:00+00:00
[2024-10-01T08:52:41.667+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1224) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-01T08:52:41.671+0000] {standard_task_runner.py:72} INFO - Started process 1270 to run task
[2024-10-01T08:52:41.678+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'remove_file', 'scheduled__2024-09-05T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpbuo7t2bz']
[2024-10-01T08:52:41.685+0000] {standard_task_runner.py:105} INFO - Job 107: Subtask remove_file
[2024-10-01T08:52:41.879+0000] {task_command.py:467} INFO - Running <TaskInstance: trigger_dag.remove_file scheduled__2024-09-05T00:00:00+00:00 [running]> on host 7a112cbb4731
[2024-10-01T08:52:42.136+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='remove_file' AIRFLOW_CTX_EXECUTION_DATE='2024-09-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-05T00:00:00+00:00'
[2024-10-01T08:52:42.140+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-01T08:52:42.145+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-01T08:52:42.146+0000] {logging_mixin.py:190} INFO - Current task name:remove_file state:running start_date:2024-10-01 08:52:41.565331+00:00
[2024-10-01T08:52:42.147+0000] {logging_mixin.py:190} INFO - Dag name:trigger_dag and current dag run status:running
[2024-10-01T08:52:42.152+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-01T08:52:42.154+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-01T08:52:42.161+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'rm /data/run']
[2024-10-01T08:52:42.175+0000] {subprocess.py:86} INFO - Output:
[2024-10-01T08:52:42.177+0000] {subprocess.py:93} INFO - rm: cannot remove '/data/run': No such file or directory
[2024-10-01T08:52:42.177+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-01T08:52:42.224+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-01T08:52:42.233+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-01T08:52:42.235+0000] {logging_mixin.py:190} INFO - Task start:2024-10-01 08:52:41.565331+00:00 end:2024-10-01 08:52:42.232625+00:00 duration:0.667294
[2024-10-01T08:52:42.236+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): remove_file> dag:<DAG: trigger_dag> dagrun:<DagRun trigger_dag @ 2024-09-05 00:00:00+00:00: scheduled__2024-09-05T00:00:00+00:00, state:running, queued_at: 2024-10-01 08:52:35.729312+00:00. externally triggered: False>
[2024-10-01T08:52:42.240+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2024-10-01T08:52:42.244+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=trigger_dag, task_id=remove_file, run_id=scheduled__2024-09-05T00:00:00+00:00, execution_date=20240905T000000, start_date=20241001T085241, end_date=20241001T085242
[2024-10-01T08:52:42.288+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-01T08:52:42.296+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 107 for task remove_file (Bash command failed. The command returned a non-zero exit code 1.; 1270)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-01T08:52:42.323+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-01T08:52:42.369+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T08:52:42.374+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
