[2024-10-04T09:46:54.078+0000] {processor.py:186} INFO - Started process (PID=43) to work on /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:46:54.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-10-04T09:46:54.082+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:46:54.082+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:46:54.126+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:46:54.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 35, in <module>
    task_check_sensor = ExternalTaskSensor(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 473, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'external_dag_id'
[2024-10-04T09:46:54.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:46:54.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.066 seconds
[2024-10-04T09:47:24.999+0000] {processor.py:186} INFO - Started process (PID=119) to work on /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:47:25.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-10-04T09:47:25.003+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:47:25.003+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:47:25.028+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:47:25.027+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 35, in <module>
    task_check_sensor = ExternalTaskSensor(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 473, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'external_dag_id'
[2024-10-04T09:47:25.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:47:25.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.041 seconds
[2024-10-04T09:47:55.777+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:47:55.778+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-10-04T09:47:55.780+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:47:55.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:47:55.806+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:47:55.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 35, in <module>
    task_check_sensor = ExternalTaskSensor(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 473, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'external_dag_id'
[2024-10-04T09:47:55.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:47:55.817+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.045 seconds
[2024-10-04T09:48:26.518+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:48:26.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-10-04T09:48:26.522+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:48:26.522+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:48:26.548+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:48:26.546+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 35, in <module>
    task_check_sensor = ExternalTaskSensor(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 473, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'external_dag_id'
[2024-10-04T09:48:26.548+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:48:26.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.044 seconds
[2024-10-04T09:48:57.024+0000] {processor.py:186} INFO - Started process (PID=320) to work on /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:48:57.025+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-10-04T09:48:57.028+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:48:57.027+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:48:57.055+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:48:57.054+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 35, in <module>
    task_check_sensor = ExternalTaskSensor(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 473, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'external_dag_id'
[2024-10-04T09:48:57.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:48:57.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.044 seconds
[2024-10-04T09:49:27.617+0000] {processor.py:186} INFO - Started process (PID=393) to work on /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:49:27.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-10-04T09:49:27.620+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:49:27.620+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:49:27.640+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:49:27.639+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 35, in <module>
    task_check_sensor = ExternalTaskSensor(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 473, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'external_dag_id'
[2024-10-04T09:49:27.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:49:27.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.035 seconds
[2024-10-04T09:49:58.045+0000] {processor.py:186} INFO - Started process (PID=460) to work on /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:49:58.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-10-04T09:49:58.049+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:49:58.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:49:58.070+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:49:58.069+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 35, in <module>
    task_check_sensor = ExternalTaskSensor(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 473, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'external_dag_id'
[2024-10-04T09:49:58.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:49:58.078+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.038 seconds
[2024-10-04T09:50:28.432+0000] {processor.py:186} INFO - Started process (PID=527) to work on /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:50:28.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-10-04T09:50:28.436+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:50:28.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:50:28.459+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:50:28.458+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 35, in <module>
    task_check_sensor = ExternalTaskSensor(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 473, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'external_dag_id'
[2024-10-04T09:50:28.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:50:28.467+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.043 seconds
[2024-10-04T09:50:58.896+0000] {processor.py:186} INFO - Started process (PID=594) to work on /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:50:58.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-10-04T09:50:58.901+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:50:58.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:50:58.931+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:50:58.930+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 35, in <module>
    task_check_sensor = ExternalTaskSensor(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 473, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'external_dag_id'
[2024-10-04T09:50:58.932+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:50:58.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.052 seconds
[2024-10-04T09:51:29.636+0000] {processor.py:186} INFO - Started process (PID=661) to work on /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:51:29.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-10-04T09:51:29.640+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:51:29.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:51:29.662+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:51:29.661+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 35, in <module>
    task_check_sensor = ExternalTaskSensor(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 473, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'external_dag_id'
[2024-10-04T09:51:29.663+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:51:29.670+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.040 seconds
[2024-10-04T09:52:00.068+0000] {processor.py:186} INFO - Started process (PID=728) to work on /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:52:00.069+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/trigger_dag.py for tasks to queue
[2024-10-04T09:52:00.072+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:52:00.072+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:52:00.106+0000] {logging_mixin.py:190} INFO - [2024-10-04T09:52:00.105+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/trigger_dag.py", line 35, in <module>
    task_check_sensor = ExternalTaskSensor(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 473, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'external_dag_id'
[2024-10-04T09:52:00.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/trigger_dag.py
[2024-10-04T09:52:00.113+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/trigger_dag.py took 0.052 seconds
